patch pfrx in publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -19,6 +19,17 @@ jobs:
       with:
         channel: 'stable'
     - run: flutter pub get
+    - name: Patch pdfrx
+      run: |
+        PDFRX_PATH=$(find $HOME/.pub-cache -type d -name "pdfrx*" | head -n 1)
+        CMAKE_FILE="$PDFRX_PATH/android/CMakeLists.txt"
+        if [ -f "$CMAKE_FILE" ]; then
+          sed -i '2i add_link_options("LINKER:--build-id=none")' "$CMAKE_FILE"
+          echo "Patched CMakeLists.txt in $CMAKE_FILE"
+        else
+          echo "CMakeLists.txt not found in expected location"
+          exit 1
+        fi
     - name: Decode Keystore
       run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
